trigger:
- none

variables:
- group: GitHubPAT

parameters:
- name: teamName
  displayName: Team Name
  type: string
  default: 'default-team'

- name: realmName
  displayName: Realm Name
  type: string
  default: 'default-realm'

jobs:
- job: BuildAndRun
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
      pip install -r requirements_tested.txt
    displayName: 'Set up Python environment'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'GitOpsServiceConnection'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "Syncing Github project"
        git clone https://$(GitHub_PAT)@github.com/MateyN/GitOps-Project.git
    env:
      GitHub_PAT: $(GitHub_PAT)
    displayName: 'Sync Github project'

  - script: |
      echo "Team Name: ${{ parameters.teamName }}"
      echo "Realm Name: ${{ parameters.realmName }}"
      pwd
      source venv/bin/activate
      export PYTHONPATH="${PYTHONPATH}:/home/mnikolov/pros-azure/aks/py/lib"
      sleep 10
      echo "PYTHONPATH is set to: $PYTHONPATH"
      sleep 10
      python3 rgCreateUpdate.py $(Build.SourcesDirectory)/home/mnikolov/gitgit/configs/${{ parameters.teamName }}.yml ${{ parameters.realmName }}
    displayName: 'Run rgCreateUpdate.py script'
