trigger:
- none

variables:
- group: GitHubPAT
- group: BitbucketSecrets

parameters:
- name: teamName
  displayName: Team Name
  type: string
  default: 'default-team'

- name: realmName
  displayName: Realm Name
  type: string
  default: 'default-realm'

jobs:
- job: BuildAndRun
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
      pip install -r requirements_tested.txt
    displayName: 'Set up Python environment'

  - script: |
      echo "Testing connectivity to Bitbucket/Stash..."
      ssh -o StrictHostKeyChecking=no git@stash.pros.com exit
    displayName: 'Test SSH Connectivity to Bitbucket/Stash'
    env:
      SSH_PRIVATE_KEY: $(SSH_PRIVATE_KEY)

  - script: |
      echo "Syncing GitHub project"
      git clone https://$(GitHub_PAT)@github.com/MateyN/GitOps-Project.git
    env:
      GitHub_PAT: $(GitHub_PAT)
    displayName: 'Sync GitHub project'

  - script: |
      echo "Syncing Bitbucket project"
      git clone ssh://git@stash.pros.com/devops/pros-azure.git
    displayName: 'Sync Bitbucket project'
    env:
      SSH_PRIVATE_KEY: $(SSH_PRIVATE_KEY)

  - script: |
      echo "Team Name: ${{ parameters.teamName }}"
      echo "Realm Name: ${{ parameters.realmName }}"
      pwd
      source venv/bin/activate
      export PYTHONPATH="${PYTHONPATH}:$(Build.SourcesDirectory)/pros-azure/aks/py/lib"
      python3 rgCreateUpdate.py $(Build.SourcesDirectory)/GitOps-Project/configs/${{ parameters.teamName }}.yml ${{ parameters.realmName }}
    displayName: 'Run rgCreateUpdate.py script'
