trigger:
- none

variables:
- group: GitHubPAT
- group: StashPAT

parameters:
- name: teamName
  displayName: Team Name
  type: string
  default: 'default-team'

- name: realmName
  displayName: Realm Name
  type: string
  default: 'default-realm'

jobs:
- job: BuildAndRun
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
      pip install -r requirements_tested.txt
    displayName: 'Set up Python environment'

  - task: AzureCLI@1
    inputs:
      azureSubscription: 'GitOpsServiceConnection'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "Syncing Bitbucket repository"
        git clone https://$(StashPAT)@stash.pros.com/scm/devops/pros-azure.git
    env:
      BitBucketPAT: $(StashPAT)
    displayName: 'Sync Bitbucket repository'

  - task: AzureCLI@1
    inputs:
      azureSubscription: 'GitOpsServiceConnection'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "Syncing GitHub repo"
        git clone https://$(GitHub_PAT)@github.com/MateyN/GitOps-Project.git
    env:
      GitHub_PAT: $(GitHub_PAT)
    displayName: 'Sync GitHub repo'

  - script: |
      echo "Team Name: ${{ parameters.teamName }}"
      echo "Realm Name: ${{ parameters.realmName }}"
      source venv/bin/activate
      export PYTHONPATH="${PYTHONPATH}:${BUILD_SOURCESDIRECTORY}/pros-azure/aks/py/lib"
      echo "PYTHONPATH is set to: $PYTHONPATH"
      python3 ${BUILD_SOURCESDIRECTORY}/GitOps-Project/rgCreateUpdate.py ${BUILD_SOURCESDIRECTORY}/GitOps-Project/configs/${{ parameters.teamName }}.yml ${{ parameters.realmName }}
    displayName: 'Run rgCreateUpdate.py script'
